# Generated by Django 4.2.4 on 2023-09-04 07:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubRubric",
            fields=[],
            options={
                "verbose_name": "Подрубрика",
                "verbose_name_plural": "Подрубрики",
                "ordering": (
                    "super_rubric__order",
                    "super_rubric__name",
                    "order",
                    "name",
                ),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("bboard.rubric",),
        ),
        migrations.CreateModel(
            name="SuperRubric",
            fields=[],
            options={
                "verbose_name": "Надрубрика",
                "verbose_name_plural": "Надрубрики",
                "ordering": ("order", "name"),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("bboard.rubric",),
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="rubric",
            name="super_rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bboard.superrubric",
                verbose_name="Надрубрика",
            ),
        ),
    ]
