# Generated by Django 4.2.4 on 2023-09-05 14:29

import bboard.utilities
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0002_rubric_subrubric_superrubric_rubric_super_rubric"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40, verbose_name="Товар")),
                ("content", models.TextField(verbose_name="Описание")),
                ("price", models.FloatField(default=0, verbose_name="Цена")),
                ("contacts", models.TextField(verbose_name="Контакты")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=bboard.utilities.get_timestamp_path,
                        verbose_name="Изображения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Выводить в списке?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор обновления",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bboard.subrubric",
                        verbose_name="Рубрика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=30, verbose_name="Автор")),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Выводить на экран?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Опубликован"
                    ),
                ),
                (
                    "bb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bboard.bb",
                        verbose_name="Объявления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdditionalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=bboard.utilities.get_timestamp_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "bb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bboard.bb",
                        verbose_name="Объявление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительная иллюстрация",
                "verbose_name_plural": "Дополнительные иллюстрации",
            },
        ),
    ]
