# Generated by Django 4.2.4 on 2023-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0003_bb_comment_additionalimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rubric",
            name="name",
            field=models.CharField(
                db_index=True, max_length=20, verbose_name="Название"
            ),
        ),
    ]
